import os

AWS_REGION = os.environ.get("REGION")
DISCORD_BOT_TOKEN = os.environ.get("DISCORD_BOT_TOKEN")
DYNAMODB_TABLE_NAME = os.environ.get("DYNAMODB_TABLE_NAME")
SQS_REMOVE_ROLE_QUEUE_URL = os.environ.get("REMOVE_ROLE_QUEUE_URL")
GOOGLE_SHEETS_SECRET_NAME = os.environ.get("GOOGLE_SHEETS_SECRET_NAME")
GOOGLE_SERVICE_ACCOUNT_EMAIL = os.environ.get("GOOGLE_SERVICE_ACCOUNT_EMAIL")
