name: 'Read Shared Config'
description: 'Reads all variables from workflow_vars.yml and sets them as outputs dynamically.'
inputs:
  config_file:
    description: 'Path to the config YAML file to read.'
    required: false
    default: 'workflow_vars.yml'
runs:
  using: 'composite'
  steps:
    - name: Read config YAML and set outputs
      id: read_config
      shell: node
      run: |
        const fs = require('fs');
        const yaml = require('js-yaml');
        const configFile = process.env.CONFIG_FILE || 'workflow_vars.yml';
        const config = yaml.load(fs.readFileSync(configFile, 'utf8'));
        for (const [key, value] of Object.entries(config)) {
          console.log(`::set-output name=${key}::${value}`);
        }
      env:
        NODE_OPTIONS: '--no-warnings'
        CONFIG_FILE: ${{ inputs.config_file }}
