on:
  workflow_call:
    inputs:
      deployment_env:
        description: Environment to deploy to (e.g., dev, prod)
        required: true
        type: string
      aws_region:
        description: AWS Region to deploy to
        required: true
        type: string
      hcp_terraform_org:
        description: HCP Terraform Organization name
        required: true
        type: string
      hcp_terraform_workspace:
        description: HCP Terraform Workspace name
        required: true
        type: string
      hcp_terraform_project:
        description: HCP Terraform Project name
        required: true
        type: string
    secrets:
      TF_API_TOKEN:
        required: true
      GH_ACTIONS_PAT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Compose the full workspace name with environment suffix
      FULL_TFC_WORKSPACE: ${{ inputs.hcp_terraform_workspace }}-${{ inputs.deployment_env }}

    steps:
      - name: Setup HCP Terraform Workspace
        id: setup_workspace
        uses: chzylee/action-workflow-hcp-terraform-workspace-setup@v1.1.0
        with:
          tfc_organization: ${{ env.hcp_terraform_org }}
          tfc_workspace: ${{ env.FULL_TFC_WORKSPACE }}
          tfc_project: ${{ env.hcp_terraform_project }}
          tfc_token: ${{ secrets.TF_API_TOKEN }}

      - name: Attach IAM Permissions Variable Set to this Workspace
        uses: chzylee/action-workflow-hcp-terraform-var-set-attach@v1.0.1
        with:
          tfc_organization: ${{ env.hcp_terraform_org }}
          tfc_workspace_id: ${{ steps.setup_workspace.outputs.workspace_id }}
          tfc_token: ${{ secrets.TF_API_TOKEN }}
          var_set_name: ${{ vars.AWS_TF_ROLE_VARSET_LAMB_APIGW_DDB }}
          # Need permissions for Lambda, API Gateway, and DynamoDB

      - name: Deploy Workspace Config via HCP Terraform
        uses: chzylee/action-workflow-hcp-terraform-run@v1.1.1
        with:
          terraform_directory: ./terraform/workspace_config # Action run from context of the repository root
          tfc_organization: ${{ env.hcp_terraform_org }}
          tfc_workspace: ${{ env.FULL_TFC_WORKSPACE }}
          tfc_token: ${{ secrets.TF_API_TOKEN }}

      - name: Deploy Application Config via HCP Terraform
        uses: chzylee/action-workflow-hcp-terraform-run@v1.1.1
        with:
          terraform_directory: ./terraform/application # Action run from context of the repository root
          tfc_organization: ${{ env.hcp_terraform_org }}
          tfc_workspace: ${{ env.FULL_TFC_WORKSPACE }}
          tfc_token: ${{ secrets.TF_API_TOKEN }}
