name: Dev Pipeline

on:
  # Trigger on push to branches excluding main.
  push:
    branches-ignore:
      - main
    tags:
      - '!*' # Avoid accidental trigger on tag creation.

permissions:
  contents: write # This is required for actions/checkout and tag creation

jobs:
  Deploy:
    uses: ./.github/workflows/action_deploy.yml
    with:
      deployment_env: 'dev'
      aws_region: 'us-east-2'
      hcp_terraform_org: 'enpicie'
      hcp_terraform_workspace: 'startgg-bracket-helper-bot-dev'
      hcp_terraform_project: 'AWS-FGC'
    secrets: inherit
