name: Release Pipeline

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Trigger only when tag with version (e.g. 1.0.0) is pushed.
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true

permissions:
  contents: write # This is required for actions/checkout and tag creation

jobs:
  read-config:
    uses: ./.github/workflows/workflow-read-config.yml
    with:
      config_file: ./.github/workflows/workflow-vars.yml
      # Config file defines:
      #   app_name, aws_region, hcp_terraform_org, hcp_terraform_project

  deploy:
    needs: read-config
    uses: ./.github/workflows/workflow-deploy.yml
    with:
      app_name: ${{ needs.read-config.outputs.app_name }}
      aws_region: ${{ needs.read-config.outputs.aws_region }}
      hcp_terraform_org: ${{ needs.read-config.outputs.hcp_terraform_org }}
      hcp_terraform_project: ${{ needs.read-config.outputs.hcp_terraform_project }}
      deployment_env: 'prod'
      artifact_s3_bucket: 'enpicie-prod-lambda-artifacts'
      hcp_terraform_workspace: ${{ needs.read-config.outputs.app_name }}-prod
    secrets: inherit
