name: Release Pipeline

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Trigger only when tag with version (e.g. 1.0.0) is pushed.
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true

permissions:
  contents: write # This is required for actions/checkout and tag creation

jobs:
  Deploy:
    uses: ./.github/workflows/action_deploy.yml
    with:
      deployment_env: 'prod'
      aws_region: 'us-east-2'
      hcp_terraform_org: 'enpicie'
      hcp_terraform_workspace: 'startgg-bracket-helper-bot-prod'
      hcp_terraform_project: 'AWS-FGC'
    secrets: inherit
