name: Release Pipeline

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Trigger only when tag with version (e.g. 1.0.0) is pushed.
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load shared config file into GitHub Actions env
        run: |
          set -a
          source ./.github/workflows/config.env
          set +a
          env | grep -v '^_' >> $GITHUB_ENV

      - name: Run deploy workflow
        uses: ./.github/workflows/workflow-deploy.yml
        with:
          app_name: ${{ env.APP_NAME }}
          aws_region: ${{ env.AWS_REGION }}
          hcp_terraform_org: ${{ env.HCP_TERRAFORM_ORG }}
          hcp_terraform_project: ${{ env.HCP_TERRAFORM_PROJECT }}
          deployment_env: 'prod'
          artifact_s3_bucket: 'enpicie-prod-lambda-artifacts'
          hcp_terraform_workspace: ${{ env.APP_NAME }}-prod
        secrets: inherit
