name: 'Read Shared Config'
on:
  workflow_call:
    inputs:
      config_file:
        description: 'Path to the config YAML file to read.'
        required: false
        default: 'workflow_vars.yml'
    outputs:
      app_name:
        description: 'Application name'
      aws_region:
        description: 'AWS region'
      artifact_s3_bucket:
        description: 'S3 bucket name'
      deployment_env:
        description: 'Deployment environment'
jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.read_config.outputs.app_name }}
      aws_region: ${{ steps.read_config.outputs.aws_region }}
      artifact_s3_bucket: ${{ steps.read_config.outputs.artifact_s3_bucket }}
      deployment_env: ${{ steps.read_config.outputs.deployment_env }}
    steps:
      - uses: actions/checkout@v4
      - name: Read config YAML and set outputs
        id: read_config
        shell: node
        run: |
          const fs = require('fs');
          const yaml = require('js-yaml');
          const configFile = process.env.CONFIG_FILE || 'workflow_vars.yml';
          const config = yaml.load(fs.readFileSync(configFile, 'utf8'));
          for (const [key, value] of Object.entries(config)) {
            console.log(`::set-output name=${key}::${value}`);
          }
        env:
          NODE_OPTIONS: '--no-warnings'
          CONFIG_FILE: ${{ inputs.config_file }}
